### PR TITLE
Update Readme with md

### PR DESCRIPTION
**Pull request by nepython**
I have updated the README with the link. Also, to the already nicely prepared README by @NidheeshJain, added a bit of **md**, hope it doesn't matter. :smiley:

### CODE REVIEW

**Comment by nepython** [comment]
@NidheeshJain, can you please check it. 
* Also, fun-fact I found that Amazon never publicly launched such a statement (or atleast I didn't find it). So,I have  updated the title accordingly.
* Also, I have used **ul** rather than **ol**, as I found it is preferred in md.
* Converted the last two lines to a single para, since they are more or less in continuation. So, it looked better.

**Comment by NidheeshJain** [comment]
It looks great!
However, I would suggest to keep the list ordered only as the aims written there are meant to be accomplished one after the other.

**Review by NidheeshJain — CHANGES_REQUESTED** [review]
It looks great!
However, I would suggest to keep the list ordered only, as the aims written there are meant to be accomplished one after the other.

**Comment by nepython** [comment]
> However, I would suggest to keep the list ordered only, as the aims written there are meant to be accomplished one after the other.

Made the changes. :grinning:

**Review by NidheeshJain — APPROVED** [review]
Nice!

**Pull request merged**
